language:
    - c
dist:
    - trusty
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get install -y autoconf-archive
before_script:
    - autoconf --version
    - automake --version
script:
    - autoreconf --install
    - ./configure
    - make V=1 -j4 clean all
after_success:
    - ./hello_c
